In [27]:
import numpy as np

In [28]:
# 1d array
d1 = np.array([1,2,3,4,5])
d1

array([1, 2, 3, 4, 5])

In [29]:
# 2d array
d2 = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15]
])

In [30]:
# 3D array
d3 = np.array([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ],
    [
        list(range(10, 13)),
        list(range(13, 16)),
        list(range(16, 19))
    ]
])
d3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [31]:
np.arange(0,5).dtype

dtype('int32')

In [32]:
d1.shape

(5,)

In [33]:
d2.shape

(3, 5)

In [34]:
d3.shape

(2, 3, 3)

In [35]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [36]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [37]:
marks = np.array(list(map(int, [np.random.randint(0,100) for i in range(20)])))

In [38]:
marks.sort()
marks

array([11, 12, 17, 20, 22, 25, 34, 41, 41, 44, 44, 49, 70, 79, 79, 90, 91,
       95, 98, 98])

In [39]:
np.array(list(reversed(marks)))

array([98, 98, 95, 91, 90, 79, 79, 70, 49, 44, 44, 41, 41, 34, 25, 22, 20,
       17, 12, 11])

In [40]:
marks_copy = np.copy(marks)
marks_copy

array([11, 12, 17, 20, 22, 25, 34, 41, 41, 44, 44, 49, 70, 79, 79, 90, 91,
       95, 98, 98])

In [41]:
np.eye(5).reshape(1,25)

array([[1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 1., 0., 0., 0., 0., 0., 1.]])

In [42]:
txt = np.arange(1,10).reshape(3,3)
txt

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
np.concatenate(txt, np.array([10,11,12]), axis=1)

TypeError: concatenate() got multiple values for argument 'axis'

In [44]:
fxf = np.eye(4)
fxf + 4

array([[5., 4., 4., 4.],
       [4., 5., 4., 4.],
       [4., 4., 5., 4.],
       [4., 4., 4., 5.]])

In [45]:
# 13
a = np.linspace(0.1, 10.1, 10)
np.ceil(a)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 11.])

In [46]:
np.floor(a)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8., 10.])

In [47]:
np.round(a)

array([ 0.,  1.,  2.,  3.,  5.,  6.,  7.,  8.,  9., 10.])

In [48]:
#min max var, std
arr = np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [49]:
arr.min()

1

In [50]:
arr.max()

25

In [51]:
arr.var()

52.0

In [52]:
arr.std()

7.211102550927978

In [60]:
arr = np.arange(10, dtype=float)
arr

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [64]:
arr[:] = np.NaN
arr[6] = 200
arr

array([ nan,  nan,  nan,  nan,  nan,  nan, 200.,  nan,  nan,  nan])

In [67]:
arr = np.arange(100, 151)
arr

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150])

In [70]:
arr_rev = np.array(list(reversed(arr)))
arr_rev

array([150, 149, 148, 147, 146, 145, 144, 143, 142, 141, 140, 139, 138,
       137, 136, 135, 134, 133, 132, 131, 130, 129, 128, 127, 126, 125,
       124, 123, 122, 121, 120, 119, 118, 117, 116, 115, 114, 113, 112,
       111, 110, 109, 108, 107, 106, 105, 104, 103, 102, 101, 100])

In [71]:
np.arange(0,25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [72]:
arr = np.array([1,0,2,0,0,4,0,8])
[i for i in range(len(arr)) if arr[i] != 0] 

[0, 2, 5, 7]

In [76]:
arr = np.ones(100, dtype=np.int32).reshape(10,10)
arr

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [80]:
arr[1:9, 1:9] = 0
arr 

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [100]:
arr = np.ones(64,dtype=np.int16).reshape(8,8)
arr

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]], dtype=int16)

In [101]:
arr[::2, ::2] = 0

In [102]:
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]], dtype=int16)

In [104]:
arr[1::2, 1::2] = 0

In [105]:
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]], dtype=int16)

In [106]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.ones(9).reshape(3,3)

In [107]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [108]:
arr2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [109]:
np.add(arr1, arr2)

array([[ 2.,  3.,  4.],
       [ 5.,  6.,  7.],
       [ 8.,  9., 10.]])

In [110]:
np.multiply(arr1, arr2)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [111]:
np.subtract(arr1, arr2)

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [112]:
np.divide(arr1, arr2)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])